import type { Metadata } from "next";
import "./globals.css";
import { russo_one } from "@/components/ui/font";
import AuthProvider from "./provider/auth";
import UiProvider from "./provider/uiProvider";

export const metadata: Metadata = {
  title: "Band",
  description: "Generated by Band",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${russo_one.className} antialiased`}
      >
        {/* <AuthProvider> */}
        <UiProvider>
          {children}
        </UiProvider>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
