import type { Metadata } from "next";
import "./globals.css";
import { russo_one } from "@/components/ui/font";
import AuthProvider from "./provider/auth";
import UiProvider from "./provider/uiProvider";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

export const metadata: Metadata = {
  title: "Band",
  description: "Generated by Band",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${russo_one.className} antialiased body`}
      >
        {/* <AuthProvider> */}
        <UiProvider>
          <div className="container">
            <Header />
            {children}
            <Footer />
          </div>
        </UiProvider>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
